import { Translation } from "../types";

export const fr: Translation = {
    addComponent: "Ajouter un composant",
    iconFor: "Icône pour",
    slotAddComponent: "Ajouter un composant",
    add: "Ajouter",
    width: "Largeur",
    height: "Hauteur",
    orientation: "Orientation",
    desktop: "Ordinateur",
    tablet: "Tablette",
    mobile: "Mobile",
    richTextHeading: "Corps",
    richTextFontFamily: "Police",
    richTextFontSize: "Taille",
    richTextFontWeight: "Graisse",
    richTextStyle: "Style",
    richTextDecoration: "Décoration",
    richTextLists: "Listes",
    richTextTextColor: "Couleur du texte",
    richTextBackgroundColor: "Couleur de fond",
    richTextAlignment: "Alignement",
    richTextNoColor: "Aucune couleur",
    richTextBold: "Gras",
    richTextItalic: "Italique",
    richTextUnderline: "Souligné",
    richTextStrike: "Barré",
    richTextBulletList: "Liste à puces",
    richTextOrderedList: "Liste numérotée",
    richTextAlignLeft: "Aligner à gauche",
    richTextAlignCenter: "Centrer",
    richTextAlignRight: "Aligner à droite",
    richTextAlignJustify: "Justifier",
    richTextBoldShort: "G",
    richTextItalicShort: "I",
    richTextUnderlineShort: "S",
    richTextStrikeShort: "B",
    richTextBulletListShort: "Puces",
    richTextOrderedListShort: "1.",
    richTextAlignLeftShort: "G",
    richTextAlignCenterShort: "C",
    richTextAlignRightShort: "D",
    richTextAlignJustifyShort: "J",
};
